name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      issues: write
      pull-requests: write
      actions: read
      checks: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set deployment variables
      id: vars
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "deploy_path=${{ secrets.DEPLOY_PATH }}" >> $GITHUB_OUTPUT
          echo "app_url=https://crm-app.maboussole.net" >> $GITHUB_OUTPUT
          echo "app_env=production" >> $GITHUB_OUTPUT
          echo "app_debug=false" >> $GITHUB_OUTPUT
        else
          echo "deploy_path=${{ secrets.STAGING_DEPLOY_PATH }}" >> $GITHUB_OUTPUT
          echo "app_url=https://staging-crm-app.maboussole.net" >> $GITHUB_OUTPUT
          echo "app_env=staging" >> $GITHUB_OUTPUT
          echo "app_debug=true" >> $GITHUB_OUTPUT
        fi

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Configure Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy Application
      env:
        DEPLOY_PATH: ${{ steps.vars.outputs.deploy_path }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        echo "Déploiement vers ${{ steps.vars.outputs.app_env }} en cours..."
        
        ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "
          set -e  # Arrêter le script en cas d'erreur
          
          # Définir le chemin de déploiement
          DEPLOY_PATH='${DEPLOY_PATH}'
          
          # Vérifier que le chemin est défini
          if [ -z \"\$DEPLOY_PATH\" ]; then
            echo 'Error: DEPLOY_PATH is not set'
            exit 1
          fi
          
          echo \"Using deploy path: \$DEPLOY_PATH\"
          
          # Vérification des commandes requises
          command -v git >/dev/null 2>&1 || { echo 'git is required but not installed.' >&2; exit 1; }
          command -v composer >/dev/null 2>&1 || { echo 'composer is required but not installed.' >&2; exit 1; }
          command -v npm >/dev/null 2>&1 || { echo 'npm is required but not installed.' >&2; exit 1; }
            
          # Navigation vers le répertoire de déploiement
          cd \"\$DEPLOY_PATH\" || exit 1
          
          # Sauvegarde du .env s'il existe
          if [ -f .env ]; then
            cp .env /tmp/env.temp
          fi
          
          # Nettoyage et initialisation du dépôt Git
          echo 'Configuration du dépôt Git...'
          if [ -d .git ]; then
            # Si un dépôt existe déjà, on le met à jour
            git fetch origin
            git checkout -f ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
          else
            # Si pas de dépôt, on nettoie et on clone
            rm -rf * .[^.]*
            git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/digitalcigit/maboussoleapp-v2.git .
            git checkout ${{ github.ref_name }}
          fi
          
          # Restauration du .env sauvegardé
          if [ -f /tmp/env.temp ]; then
            mv /tmp/env.temp .env
          fi
          
          # Configuration des permissions
          echo 'Configuration des permissions...'
          find . -type f -exec chmod 664 {} \;
          find . -type d -exec chmod 775 {} \;
          
          # Restauration du fichier .env
          echo 'Restauration du fichier .env...'
          cp /var/www/laravel/.env \"\$DEPLOY_PATH/.env\"
          chmod 664 .env
          
          # Installation des dépendances
          echo 'Installation des dépendances...'
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm ci
          npm run build
          
          # Configuration des dossiers storage et cache
          echo 'Configuration des dossiers storage et cache...'
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p storage/logs
          mkdir -p bootstrap/cache
          chmod -R 775 storage bootstrap/cache
          
          # Création des fichiers de log
          echo 'Création des fichiers de log...'
          touch storage/logs/laravel.log
          chmod 664 storage/logs/laravel.log
          
          # Configuration de Laravel
          echo 'Configuration de Laravel...'
          php artisan storage:link --force --verbose
          php artisan optimize:clear --verbose
          
          # Test de connexion à la base de données
          echo 'Test de connexion à la base de données...'
          php artisan tinker --execute=\"echo DB::connection()->getDatabaseName();\"
          
          # Migrations et seeders
          echo 'Exécution des migrations...'
          php artisan migrate --force --verbose
          
          # Création des rôles et permissions
          echo 'Création des rôles et permissions...'
          php artisan db:seed --class=RoleAndPermissionSeeder --force --verbose
          
          # Exécution du seeder pour l'utilisateur admin
          echo 'Création de l'\''utilisateur admin via seeder...'
          php artisan db:seed --class=AdminUserSeeder --force --verbose
          
          echo 'Déploiement terminé avec succès!'
        "

    - name: Notify Slack on Failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": " Le déploiement sur ${{ steps.vars.outputs.app_env }} a échoué !\nBranche: ${{ github.ref_name }}\nCommit: ${{ github.sha }}"
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
