name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      issues: write
      pull-requests: write
      actions: read
      checks: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set deployment variables
      id: vars
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "deploy_path=${{ secrets.DEPLOY_PATH }}" >> $GITHUB_OUTPUT
          echo "app_url=https://crm-app.maboussole.net" >> $GITHUB_OUTPUT
          echo "app_env=production" >> $GITHUB_OUTPUT
          echo "app_debug=false" >> $GITHUB_OUTPUT
        else
          echo "deploy_path=${{ secrets.STAGING_DEPLOY_PATH }}" >> $GITHUB_OUTPUT
          echo "app_url=https://staging-crm-app.maboussole.net" >> $GITHUB_OUTPUT
          echo "app_env=staging" >> $GITHUB_OUTPUT
          echo "app_debug=true" >> $GITHUB_OUTPUT
        fi

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Configure Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy Application
      env:
        DEPLOY_PATH: ${{ steps.vars.outputs.deploy_path }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        echo "Déploiement vers ${{ steps.vars.outputs.app_env }} en cours..."
        
        ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "
          set -e  # Arrêter le script en cas d'erreur
          
          # Définir le chemin de déploiement
          DEPLOY_PATH='${DEPLOY_PATH}'
          
          # Vérifier que le chemin est défini
          if [ -z \"\$DEPLOY_PATH\" ]; then
            echo 'Error: DEPLOY_PATH is not set'
            exit 1
          fi
          
          echo \"Using deploy path: \$DEPLOY_PATH\"
          
          # Vérification des commandes requises
          command -v git >/dev/null 2>&1 || { echo 'git is required but not installed.' >&2; exit 1; }
          command -v composer >/dev/null 2>&1 || { echo 'composer is required but not installed.' >&2; exit 1; }
          command -v npm >/dev/null 2>&1 || { echo 'npm is required but not installed.' >&2; exit 1; }
            
          # Vérification et nettoyage du répertoire de déploiement
          echo 'Configuration du répertoire de déploiement...'
          if [ ! -d \"\$DEPLOY_PATH\" ]; then
            echo 'Error: Le répertoire de déploiement n'\''existe pas. Veuillez le créer avec les bonnes permissions.'
            exit 1
          else
            echo 'Nettoyage du répertoire de déploiement...'
            rm -rf \"\$DEPLOY_PATH\"/*
            rm -rf \"\$DEPLOY_PATH\"/.[!.]*
          fi
            
          # Navigation vers le répertoire de déploiement
          cd \"\$DEPLOY_PATH\" || exit 1
            
          # Clone du dépôt avec le token
          echo 'Clonage du dépôt...'
          git clone --depth 1 -b ${{ github.ref_name }} https://${{ secrets.DEPLOY_TOKEN }}@github.com/digitalcigit/maboussoleapp-v2.git .
            
          # Création du fichier .env
          echo 'Configuration du fichier .env...'
          cat > .env << EOF
            APP_NAME=Ma Boussole
            APP_ENV=${{ steps.vars.outputs.app_env }}
            APP_KEY=
            APP_DEBUG=${{ steps.vars.outputs.app_debug }}
            APP_URL=${{ steps.vars.outputs.app_url }}

            LOG_CHANNEL=stack
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.STAGING_DB_HOST }}
            DB_PORT=${{ secrets.STAGING_DB_PORT }}
            DB_DATABASE=${{ secrets.STAGING_DB_DATABASE }}
            DB_USERNAME=${{ secrets.STAGING_DB_USERNAME }}
            DB_PASSWORD=${{ secrets.STAGING_DB_PASSWORD }}

            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120
          EOF

          # Vérification du contenu du .env
          echo 'Vérification du fichier .env...'
          cat .env
            
          # Installation des dépendances PHP avec plus de verbosité
          echo 'Installation des dépendances PHP...'
          composer install --no-dev --no-interaction --optimize-autoloader -v
            
          # Installation des dépendances Node.js et build avec plus de verbosité
          echo 'Installation des dépendances Node.js...'
          npm ci --verbose
          npm run build --verbose
            
          # Configuration de l'application avec plus de logs
          echo 'Configuration de l'\''application...'
          php artisan key:generate --force --verbose
          php artisan storage:link --force --verbose
            
          # Vérification du storage
          echo 'Vérification du storage...'
          ls -la storage
          ls -la public
            
          # Optimisations avec plus de verbosité
          echo 'Optimisation de l'\''application...'
          php artisan optimize:clear --verbose
          php artisan config:cache --verbose
          php artisan route:cache --verbose
          php artisan view:cache --verbose
            
          # Vérification des logs d'erreur
          echo 'Vérification des logs...'
          tail -n 50 storage/logs/laravel.log || echo "Pas de fichier de log trouvé"
            
          # Migrations avec plus de verbosité
          echo 'Vérification des migrations...'
          php artisan migrate:status --verbose
          if [ $? -eq 0 ]; then
            echo 'Exécution des migrations...'
            php artisan migrate --force --verbose
          else
            echo 'Warning: Base de données non accessible. Les migrations seront ignorées.'
          fi
            
          echo 'Déploiement terminé avec succès!'
        "

    - name: Notify Slack on Failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "❌ Le déploiement sur ${{ steps.vars.outputs.app_env }} a échoué !\nBranche: ${{ github.ref_name }}\nCommit: ${{ github.sha }}"
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
